# Generated by Django 5.0.9 on 2024-09-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='description',
        ),
        migrations.DeleteModel(
            name='CardImage',
        ),
    ]
