# Generated by Django 5.0.9 on 2024-09-26 16:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
